query AllMovies @auth(level: PUBLIC, insecureReason: "This operation is safe to expose to the public as it retrieves movie data.") {
  movies {
    id
    title
    year
    genres
    runtime
    summary
  }
}

query MyLists @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users as it retrieves their own lists.") {
  lists(where: {userId: {eq_expr: "auth.uid"}}) {
    id
    name
    public
    createdAt
    updatedAt
    description
  }
}

mutation CreateWatch($movieId: UUID!, $watchDate: Date!, $location: String) @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users as it allows them to record their own watch events.") {
  watch_insert(data: {
    movieId: $movieId,
    userId_expr: "auth.uid",
    watchDate: $watchDate,
    location: $location
  })
}

mutation AddMovieToList($listId: UUID!, $movieId: UUID!, $position: Int!) @auth(level: USER, insecureReason: "This operation is safe to expose to all logged in users as it allows them to manage movies in their own lists.") {
  listMovie_insert(data: {
    listId: $listId,
    movieId: $movieId,
    position: $position
  })
}